name: elevate_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.5.0  
  get_it:     
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  retrofit: ^4.4.0
  logger: ^2.4.0  # for logging purpose
  json_annotation: ^4.9.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator:  
  build_runner:
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  json_serializable: ^6.8.0   

flutter:
  uses-material-design: true
